const ERROR_MESSAGES: Record<string, string> = {
  wrong_domain: "Please sign in with your district Google Workspace account, not a personal Gmail account.",
  invalid_oauth_state: "Your sign-in session expired. Please try signing in again.",
  oauth_failed: "Something went wrong talking to Google during sign-in. Please try again.",
  no_profile: "Google didn't return a profile for that account. Please try again.",
  access_denied: "Sign-in was cancelled."
};

export default function Login({ error }: { error: string | null }) {
  return (
    <div className="centered">
      <div className="card login-card">
        <h1>Compliance Rule Manager</h1>
        <p>Create Gmail compliance rules and Google Drive trust rules for your organization, scoped by OU.</p>
        {error && <div className="banner banner-error">{ERROR_MESSAGES[error] ?? "Sign-in failed. Please try again."}</div>}
        <a className="google-signin-button" href="/auth/google">
          Sign in with Google
        </a>
        <p className="fine-print">
          You must sign in with a Google Workspace admin account on your district's domain. Regular staff/student
          accounts cannot use this tool.
        </p>
        <p className="fine-print">This tool's code was generated by an AI coding assistant. See NOTICE.md in the repo for details.</p>
      </div>
    </div>
  );
}
